# Generated by Django 5.2.6 on 2025-09-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32)),
                ('category_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=128)),
                ('new_desc', models.TextField()),
                ('new_date', models.DateTimeField(auto_now_add=True)),
                ('new_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.category')),
            ],
        ),
    ]
