# Generated by Django 5.2.6 on 2025-09-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name_plural': 'Новости'},
        ),
    ]
