# Generated by Django 5.2.6 on 2025-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_category_options_alter_new_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='new_photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
