# Generated by Django 5.2.6 on 2025-09-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
